### ISSUE TITLE
Error on Lot Serial Info page "An incorrect type of extension has been requested"

### ISSUE THREAD

**Issue by scottstanaland** [Acumatica/Acumatica-LotSerialNbrAttribute-2023R1-ONWARD#6]
After deploying the latest package version that corrected the error releasing some Inventory Adjustments we are now getting this error when trying to load a serial number on the Lot Serial Info page "An incorrect type of extension has been requested"

**Comment by RobertCSternberg** [comment]
Could you provide some screenshots, reproduction steps, and the Trace details of the issue to help the developers track this down?

**Comment by scottstanaland** [comment]
Here are a few screenshots of the error and the trace screen.  I pasted the full trace log below also.

![image](https://github.com/Acumatica/Acumatica-LotSerialNbrAttribute-2023R1-ONWARD/assets/98192449/8f8045bc-a3cd-4914-840b-16488c858296)

![image](https://github.com/Acumatica/Acumatica-LotSerialNbrAttribute-2023R1-ONWARD/assets/98192449/8a8fc753-5580-4c45-b6a4-35b5772df688)

<html>
<body>

Category: | Trace
-- | --
Message: | Error: An incorrect type of extension has been requested.
Stack Trace: | at PX.Data.PXCache`1.GetExtension[Extension](TNode item)  at PX.LotSerialNbrAttribute.Ext.InventoryLotSerialMaint._(RowSelecting`1 e) in C:\Work Acumatica\Acumatica_Stash\SourceCode\Acumatica_Customization\_Common\2023R1\Acumatica-LotSerialNbrAttribute\PX.LotSertialNbrAttribute.Ext\PX.LotSerialNbrAttribute.Ext\IN\InventoryLotSerialMaint.cs:line 105  at PX.Data.PXRowSelecting.Invoke(PXCache sender, PXRowSelectingEventArgs e)  at PX.Data.PXSelectResult.executeRowSelecting()  at PX.Data.PXView.GetResult(Object[] parameters, PXFilterRow[] filters, Boolean reverseOrder, Int32 topCount, PXSearchColumn[] sorts, Boolean& overrideSort, Boolean& extFilter)  at PX.Data.PXView.Select(Object[] currents, Object[] parameters, Object[] searches, String[] sortcolumns, Boolean[] descendings, PXFilterRow[] filters, Int32& startRow, Int32 maximumRows, Int32& totalRows, String[] sortAsImplicitColumns)  at PX.Data.PXView.Select(Object[] currents, Object[] parameters, Object[] searches, String[] sortcolumns, Boolean[] descendings, PXFilterRow[] filters, Int32& startRow, Int32 maximumRows, Int32& totalRows)  at PX.Data.PXGraph.ExecuteSelect(String viewName, Object[] currents, Object[] parameters, Object[] searches, String[] sortcolumns, Boolean[] descendings, PXFilterRow[] filters, Int32& startRow, Int32 maximumRows, Int32& totalRows, Boolean shouldReadArchived)


</body>
</html>

**Comment by RobertCSternberg** [comment]
Hi!  If you give me some steps to reproduce the issue I can test it in a demo environment and confirm it is not just your environment having the issue.

**Comment by scottstanaland** [comment]
Hi Robert,

We are getting the error when we select the Lot / Serial lookup icon.  If you look at the trace screenshot it's raising that error multiple times.

**Comment by DhirenChhapgar** [comment]
This issue is resolved in today's released package.

**Comment by scottstanaland** [comment]
Thank you Dhiren!
